spring:
  application:
    name: hello-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        注册到registory才能被turbine发现
        register: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0
server:
#  端口号不能大于10000，不然服务发现不了，奶奶的
  port: 8001
logging:
  level:
    org:
      example: DEBUG
feign:
  hystrix:
    enabled: true
turbine:
  app-config: hello-consumer
  aggregator:
    cluster-config:
      - default
  cluster-name-expression: new String("default")
management:
  endpoints:
    web:
      exposure:
        include: '*'
username: China
password: "{cipher}ddde1f428371febaf84be14f169b63771585e2a35e70b874524627dbbd573661"
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://node1:8091/eureka/,http://node2:8092/eureka/,http://node3:8093/eureka/
